baseurl = "/"
languageCode = "en-us"
title = "Jennifer Barbettini"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
		name = "Jennifer Barbettini"
		description = "Full stack engineer with a strong background in JavaScript and a particular love for design and user experience | Hustler. Hacker. Get Shit Done-r"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
		#
		# What you need to do for the setup?
		#
		# - set your email address under 'email' below
		# - upload the generated site to your server
		# - send a dummy email yourself to confirm your account
		# - click the confirm link in the email from www.formspree.io
		# - you're done. Happy mailing!
	email = "jen.barbettini@gmail.com"


	# Navigation
	[params.navigation]
		brand = "Jennifer Barbettini"

		[params.navigation.links]
			about     = "The tl:dr"
			services  = "Why Me?"
			portfolio = "Recent Work"
			contact   = "Contact"


	# Hero sec
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Hi, I'm Jen."
		subtitle   = "I’m a full stack engineer with extensive experience in Javascript and Ruby <br> and a particular love for design and user experience."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "The TL:DR"
		description = "I'm currently a full-stack software engineer at Hint Health. Previously, I was Engineer #2 and a Product/QA Lead for the Customer Experience team at Gobble, where I was responsible for our public-facing marketing website, core customer-facing application, internal applications, and A/B growth initiatives.<br><br>I’m motivated by product design and real-world impact. I can (and have) spent hours ensuring my applications are pixel-perfect, and I especially enjoy turning ideas into reality.<br><br>In my spare time, I particularly enjoy creating solutions to problems that I personally have. For example, my first application was a restaurant recommendation engine, because I have always struggled with the question “what should I eat for dinner?” I’ve also recently contributed to a debugger tool to help other developers understand the protocols behind OAuth and OpenID Connect flows.<br><br>I believe in companies that encourage life outside of work, understand that thorough planning can save hours of programming, appreciate engineers with diverse backgrounds and skillsets, and value getting (sh)it done :) Bonus points if I can easily explain to my non-technical parents exactly what I do and why it's important."
		buttonText  = "Check Out My Resume"


	# Service section
	[params.services]
		headline = "Hustler. Hacker. Get Shit Done-r"

    [[params.services.list]]
      icon = "fa-puzzle-piece"
      title = "I bring more than engineering to the table"
      description = "My engineering skills are backed by extensive experience in marketing, account management, customer support, product development, and operations.  I’ve worked in small businesses and startups (including my own) and led teams from three to twenty."

    [[params.services.list]]
      icon = "fa-users"
      title = "I'm all about the team"
      description = "Because of the many hats that I have worn throughout my career, I am a team player who understands how my role can impact all other areas of the business. It’s not just about engineering; it’s about communication, teamwork, and a mutual passion to drive our product forward and faster."

    [[params.services.list]]
			icon = "fa-fighter-jet"
			title = "I excel in the tech world"
			description = "Four years ago, I relocated to pursue my dream of working for startups. I love being surrounded by people who are passionate about what they do and are driven to make an impact. I thrive on challenges and deadlines, am fanatical about the tiny details, and believe that thorough planning can save hours of programming."

    [[params.services.list]]
      icon = "fa-smile-o"
      title = "I love what I do."
      description = "There is nothing I love more than checking things off a list, figuring out how to turn an idea into reality, and creating order out of chaos. I truly enjoy tackling every aspect of the application development, from planning and wireframing to prototyping and improving features. I’m not afraid to work hard, and I’m passionate about delivering results."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

		# Contact section
		[params.contact]
			title = "Get in Touch"

			# The following social network icons are available:
			# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
			# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
			[[params.contact.social]]
				icon = "linkedin"
				link = "//www.linkedin.com/in/jenbarbettini"

			[[params.contact.social]]
				icon = "github"
				link = "//github.com/jbarbettini"

			[[params.contact.social]]
				icon = "twitter"
				link = "//twitter.com/its_jenno"

			[[params.contact.social]]
				icon = "facebook"
				link = "//www.facebook.com/jen.barbettini"

			[[params.contact.social]]
				icon = "instagram"
				link = "//www.instagram.com/itsjenno"


		[params.form]
			title = "Let's grab coffee."
			# Form fields
			name = "Your Name"
			email = "Your Email"
			message = "Tell me about your project"
			buttonText = "Send"
